package com.mycompany.client_chat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.math.BigInteger;
import java.net.Socket;
import java.awt.event.KeyEvent;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;

/**
 *
 * @author mukul
 */
public class Client_chat extends javax.swing.JFrame {

    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dout;
    static RSA rsa_Client = new RSA(2048);
    //static PublicKey pub_Server;
    static BigInteger pub_n;
    static BigInteger pub_Server;
    static boolean clave_enviada = true;
    static boolean clave_recibida = true;

    /**
     * Creates new form chat_server
     */
    public Client_chat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_area.setColumns(20);
        msg_area.setRows(15);
        msg_area.setTabSize(13);
        msg_area.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jScrollPane1.setViewportView(msg_area);

        msg_send.setText("Enviar");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });
        msg_send.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_sendKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Chat Bob");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(msg_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msg_text)
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:

        try {
            String msg = "";
            msg = msg_text.getText();
            //Cifrar el msj
            String msg_cif = rsa_Client.cifrar(msg.getBytes(), pub_Server, pub_n).toString();
            String sign = rsa_Client.sign(msg.getBytes(), rsa_Client.getPriv(), rsa_Client.getn()).toString();
            dout.writeUTF(msg_cif + "," + sign);
            System.out.println("Mensaje Enviado");
            msg_text.setText("");
            msg_area.setText(msg_area.getText() + "\n Yo: " + msg);
        } catch (Exception e) {
            //handle the exception here
        }


    }//GEN-LAST:event_msg_sendActionPerformed

    private void msg_sendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_sendKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String msg = "";
                msg = msg_text.getText();
                //Cifrar el msj
                String msg_cif = rsa_Client.cifrar(msg.getBytes(), pub_Server, pub_n).toString();
                String sign = rsa_Client.sign(msg.getBytes(), rsa_Client.getPriv(), rsa_Client.getn()).toString();
                dout.writeUTF(msg_cif + "," + sign);
                msg_text.setText("");
                msg_area.setText(msg_area.getText() + "\n Yo: " + msg);
            } catch (Exception e) {
                //handle the exception here
            }
        }
    }//GEN-LAST:event_msg_sendKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_chat().setVisible(true);
            }
        });

        try {
            String msgin = "";

            s = new Socket("127.0.0.1", 1201); // ip address is of localhost because server is running on the same mschine
            dis = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());

            while (true) {

                if (clave_recibida == true) {
                    System.out.println("Recibida");
                    String msin = dis.readUTF();
                    String[] publi = msin.split(",");
                    pub_Server = new BigInteger(publi[0]);
                    pub_n = new BigInteger(publi[1]);
                    clave_recibida = false;
                    String pub = rsa_Client.getPub().toString();
                    String n = rsa_Client.getn().toString();
                    dout.writeUTF(pub + "," + n);
                    System.out.println("Se enviaron Keys");
                } else {

                    msgin = dis.readUTF();
                    System.out.println("llego mensaje");
                    String[] msgin_aux = msgin.split(",");
                    System.out.println(msgin_aux[0]);
                    byte[] msg_aux = rsa_Client.descifrar(new BigInteger(msgin_aux[0]), rsa_Client.getPriv(), rsa_Client.getn());

                    //Verify
                    BigInteger sign = new BigInteger(msgin_aux[1]);
                    boolean verify = rsa_Client.verify(msg_aux, sign, pub_Server, pub_n);
                    System.out.println(verify);
                    if (verify == true) {
                        msg_area.setText(msg_area.getText() + "\n Alice: " + new String(msg_aux));
                    } else {
                        msg_area.setText(msg_area.getText() + "\n Alice: Mensaje no autenticado");
                    }

                }
            }
            //}

        } catch (Exception e) {
            //handle the exception here
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text;
    // End of variables declaration//GEN-END:variables
}
